### ISSUE TITLE
Пара вопросов по вашему пакету...

### ISSUE THREAD

**Issue by DaN66O** [sergray/energy-meter-mercury206#7]
Добрый день !
Установил пакет. В папке появились файлы назначение которых не описано.
Не могли бы вы подсказать назначение файлов mercury206_vcp, easy_install-3.9 и easy_install и в чем их разница ?
В данный момент уже используется Python 3.10, будут ли проблемы с этим ?
mercury206_config только создает конфигурационный файл или у него больше функций ?
Каков период опроса у mercury206_readings ? 
Не могли бы вы привести пример переназначения папки по умолчанию ${HOME}/.mercury206/config.ini
Если создать systemd сервис, то можно ли там определить файл конфигурации ? 
Прошу простить за кучу вопросов...

**Comment by sergray** [comment]
Здравствуйте, @DaN66O 

В проекте есть автоматическая [генерация консольных скриптов](https://github.com/sergray/energy-meter-mercury206/blob/master/setup.py#L28):
- `mercury206_config` - создание файла конфигурации
- `mercury206_readings` - текущие показания потребления на момент выполнения скрипта
- `mercury206_vcp` - мгновенные показания Voltage, Current, Power

 easy_install-3.9 и easy_install создаются из-за использования [setuptools](https://github.com/sergray/energy-meter-mercury206/blob/master/setup.py#L7) и видимо Python 3.9

Я уже не использую сам проект и не могу гарантировать, что он работает со всеми версиями Python 3 интерпретаторов. Поэтому могу только посоветовать пробовать запускать и смотреть как работает. Буду рад любым улучшениям и исправлениям в виде пул-запросов.

Все настройки, в т.ч. путь к файлу настроек, можно переопределить при помощи переменных окружения, которые перечислены в https://github.com/sergray/energy-meter-mercury206/blob/master/mercury206/config.py#L11
